### ISSUE TITLE
Type error in Web Chat tool.tsx: trimEnd called on string | number

### ISSUE THREAD

**Issue by malewis5** [vercel/eve#2662]
## Bug

`eve add channel/web` generates `components/ai-elements/tool.tsx` with a TypeScript error:

> Property `trimEnd` does not exist on type `string | number`.
> Property `trimEnd` does not exist on type `number`.

## Source

Introduced in 659774fdf (PR #2536 — "Refine generated Web Chat interactions").

That PR rewrote `apps/docs/registry/channel/web/components/ai-elements/tool.tsx` and added a new `getRecordValue` helper:

```ts
const getRecordValue = (value: unknown, key: string): string | number | undefined => { /* ... */ };
```

`stdout` and `stderr` are derived from it, so they widen to `string | number`:

```ts
const stdout = getRecordValue(output, "stdout") ?? (typeof output === "string" ? output : "");
const stderr = getRecordValue(output, "stderr") ?? errorText ?? "";
```

Then `.trimEnd()` is called on them, but `number` has no `trimEnd`:

```tsx
{stdout ? <span className="block">{stdout.trimEnd()}</span> : null}
{stderr ? <span className="block text-destructive">{stderr.trimEnd()}</span> : null}
```

The `number` branch exists to serve `exitCode` (line ~130 checks `typeof exitCode === "number"`), but the same return type leaks onto the display strings.

## Suggested fix

Coerce the display values to strings before calling `.trimEnd()` (keeping the helper s `number` return for `exitCode`), e.g.:

```tsx
{stdout ? <span className="block">{String(stdout).trimEnd()}</span> : null}
{stderr ? <span className="block text-destructive">{String(stderr).trimEnd()}</span> : null}
```

## Repro

1. `eve add channel/web`
2. Run `tsc` / typecheck in the generated project
3. Observe the error on `stdout.trimEnd()` / `stderr.trimEnd()` in `tool.tsx`
